"""empty message

Revision ID: dec9d2e82c87
Revises: 
Create Date: 2019-09-28 06:07:42.739453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dec9d2e82c87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('birth_place', sa.String(length=64), nullable=True),
    sa.Column('facebook_url', sa.String(length=200), nullable=True),
    sa.Column('twitter_url', sa.String(length=200), nullable=True),
    sa.Column('insta_url', sa.String(length=200), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('nationality', sa.String(length=64), nullable=True),
    sa.Column('spouse_name', sa.String(length=64), nullable=True),
    sa.Column('father_name', sa.String(length=64), nullable=True),
    sa.Column('mother_name', sa.String(length=64), nullable=True),
    sa.Column('children', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('actor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_actor_age'), ['age'], unique=False)
        batch_op.create_index(batch_op.f('ix_actor_birth_place'), ['birth_place'], unique=False)
        batch_op.create_index(batch_op.f('ix_actor_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_actor_name'), ['name'], unique=False)

    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('writer', sa.String(length=120), nullable=True),
    sa.Column('director', sa.String(length=120), nullable=True),
    sa.Column('storyline', sa.String(length=1000), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('languages', sa.String(length=120), nullable=True),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.Column('genres', sa.String(length=120), nullable=True),
    sa.Column('budget', sa.Integer(), nullable=True),
    sa.Column('box_office_domestic', sa.Integer(), nullable=True),
    sa.Column('box_office_gross', sa.Integer(), nullable=True),
    sa.Column('production_company', sa.String(length=120), nullable=True),
    sa.Column('run_time', sa.String(length=120), nullable=True),
    sa.Column('youtube', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movie_box_office_domestic'), ['box_office_domestic'], unique=False)
        batch_op.create_index(batch_op.f('ix_movie_box_office_gross'), ['box_office_gross'], unique=False)
        batch_op.create_index(batch_op.f('ix_movie_budget'), ['budget'], unique=False)
        batch_op.create_index(batch_op.f('ix_movie_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_movie_description'), ['description'], unique=False)
        batch_op.create_index(batch_op.f('ix_movie_director'), ['director'], unique=False)
        batch_op.create_index(batch_op.f('ix_movie_genres'), ['genres'], unique=False)
        batch_op.create_index(batch_op.f('ix_movie_industry'), ['industry'], unique=False)
        batch_op.create_index(batch_op.f('ix_movie_languages'), ['languages'], unique=False)
        batch_op.create_index(batch_op.f('ix_movie_production_company'), ['production_company'], unique=False)
        batch_op.create_index(batch_op.f('ix_movie_release_date'), ['release_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_movie_run_time'), ['run_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_movie_storyline'), ['storyline'], unique=False)
        batch_op.create_index(batch_op.f('ix_movie_title'), ['title'], unique=True)
        batch_op.create_index(batch_op.f('ix_movie_writer'), ['writer'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('user_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('awards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('year', sa.String(length=10), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('awards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_awards_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_awards_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_awards_year'), ['year'], unique=False)

    op.create_table('cast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=64), nullable=True),
    sa.Column('actor_name', sa.String(length=64), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cast', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cast_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cast_role_name'), ['role_name'], unique=False)

    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_likes_id'), ['id'], unique=False)

    op.create_table('ratings',
    sa.Column('rating_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('rating_id')
    )
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ratings_rating'), ['rating'], unique=False)
        batch_op.create_index(batch_op.f('ix_ratings_rating_id'), ['rating_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ratings_rating_id'))
        batch_op.drop_index(batch_op.f('ix_ratings_rating'))

    op.drop_table('ratings')
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_likes_id'))

    op.drop_table('likes')
    with op.batch_alter_table('cast', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cast_role_name'))
        batch_op.drop_index(batch_op.f('ix_cast_id'))

    op.drop_table('cast')
    with op.batch_alter_table('awards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_awards_year'))
        batch_op.drop_index(batch_op.f('ix_awards_name'))
        batch_op.drop_index(batch_op.f('ix_awards_id'))

    op.drop_table('awards')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movie_writer'))
        batch_op.drop_index(batch_op.f('ix_movie_title'))
        batch_op.drop_index(batch_op.f('ix_movie_storyline'))
        batch_op.drop_index(batch_op.f('ix_movie_run_time'))
        batch_op.drop_index(batch_op.f('ix_movie_release_date'))
        batch_op.drop_index(batch_op.f('ix_movie_production_company'))
        batch_op.drop_index(batch_op.f('ix_movie_languages'))
        batch_op.drop_index(batch_op.f('ix_movie_industry'))
        batch_op.drop_index(batch_op.f('ix_movie_genres'))
        batch_op.drop_index(batch_op.f('ix_movie_director'))
        batch_op.drop_index(batch_op.f('ix_movie_description'))
        batch_op.drop_index(batch_op.f('ix_movie_country'))
        batch_op.drop_index(batch_op.f('ix_movie_budget'))
        batch_op.drop_index(batch_op.f('ix_movie_box_office_gross'))
        batch_op.drop_index(batch_op.f('ix_movie_box_office_domestic'))

    op.drop_table('movie')
    with op.batch_alter_table('actor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_actor_name'))
        batch_op.drop_index(batch_op.f('ix_actor_id'))
        batch_op.drop_index(batch_op.f('ix_actor_birth_place'))
        batch_op.drop_index(batch_op.f('ix_actor_age'))

    op.drop_table('actor')
    # ### end Alembic commands ###
